### PR TITLE
chore(Dockerfile): use copy instead of clone again

### PR DESCRIPTION
**Pull request by codycjy**

### CODE REVIEW

**Comment by yuantuo666** [comment]
Further test on docker build process needed.

**Comment by codycjy** [comment]
For further plan, we maybe can use the github action to test the complete workflow, from installing to parsing the url and try to download the direct link. Sensitive info could be stored at secret? I think. Any way,  I have tested this Dockerfile on my machine and it works fine.

**Comment by yuantuo666** [comment]
Thanks for your contribution. I will test it and let you know the result.

For next time post PR, I would suggest you to write description part with simple words to explain what you have done and screenshot to show your work.

**Review by yuantuo666 — APPROVED** [review]
Tested: works fine.

**Pull request merged**
